---
- name: "Rust | Check for Cargo"
  shell: comand -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: "Rust | Download Cargo"
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: "Rust| Install Cargo"
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
